<?php 

class Constants {
	const HOMEPAGE_ARTICLES_COUNT = 9;
	const PROFILE_PAGE_ARTICLES_COUNT = 6;
	const SIDEBAR_ARTICLES_COUNT = 5;
	const MOOD_LANDING_PAGE_COUNT = 9;
	const POST_TAG_LANDING_PAGE_COUNT = 9;
	const SEARCH_RESULTS_COUNT = 10;
	const AUTHOR_LANDING_PAGE_COUNT = 6;
	const EXPLORE_PAGE_ARTICLES_COUNT = 6;
	
	const EXCERPT_LENGTH = 150;
	const SHARING_ENABLED = TRUE;

	const LOADMORE_COUNT = 9;
}